Changed from sha1 to sha256
Got error message on install
    Error: SHA1 mismatch
    Expected: 8a2ba434134413e16d83a6dd8d98ba5e1d3ac782a0719abc27fc6feef6ca5a82
    Actual: 27c9ebfe8470851099d3f4efe65370cf00c9b58d